controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "joint_left_wheel"
  right_wheel: "joint_right_wheel"
  wheel_separation: 0.2
  wheel_radius: 0.1
  odom_frame_id: "odom"
  base_frame_id: "link_chassis"
  enable_odom_tf: true
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.0  # m/s
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 2.0  # rad/s
